# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewTest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(default='galaxy s8', on_delete=django.db.models.deletion.CASCADE, to='viewTest.Product'),
            preserve_default=False,
        ),
    ]
