# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewTest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmenucategorie',
            name='idCategorie',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='linkmenucategorie',
            name='idMenu',
            field=models.IntegerField(),
        ),
    ]
