# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewTest', '0002_auto_20170428_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='idCategorie',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='idMerk',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
