# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewTest', '0004_auto_20170429_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='gebruiker',
            name='wachtwoord',
            field=models.CharField(default=1234, max_length=255),
            preserve_default=False,
        ),
    ]
