# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewTest', '0005_gebruiker_wachtwoord'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='fout', upload_to='productimages'),
            preserve_default=False,
        ),
    ]
